### ISSUE TITLE
Problem with datetime including timezone character Z

### ISSUE THREAD

**Issue by PMX** [art049/odmantic#102]
# Bug

_A clear and concise description of what the bug is._

Assigning default timestamp via default_factory includes a Z at the end.
[tree_api.zip](https://github.com/art049/odmantic/files/5971431/tree_api.zip)

### Current Behavior

I created the test program tree_api.py from **https://art049.github.io/odmantic/usage_fastapi/**  and enhanced it by a updated-field (see attachment).

Then I start uvicorn via: **uvicorn tree_api:app** 

Then I open the URL: **http://127.0.0.1:8000/docs#/default/create_tree_trees__put** and test the creation of a new tree object via Try it out on PUT /trees/

the generated JSON string is:
{
  "name": "string",
  "average_size": 0,
  "discovery_year": 0,
  "updated": "2021-02-12T11:22:55.542Z",
  "id": "ffffffffffffffffffffffff"
}

Note: the updated-attribute has a timestamp with a last character Z. If I change the name and id and execute it I got an error message "**datetime objects must be naive (no timeone info)
[tree_api.zip](https://github.com/art049/odmantic/files/5971421/tree_api.zip)

**"

In detail:
{
  "detail": [
    {
      "loc": [
        "body",
        "updated"
      ],
      "msg": "datetime objects must be naive (no timeone info)",
      "type": "value_error"
    }
  ]
}

If I remove the last character Z, it works fine!

### Expected behavior

... _A clear and concise description of what you expected to happen.

I expected, that the timestamp did not have the Z at the end and that it works directly.

### Environment

- ODMantic version:  0.3.2
- FastApi: 0.63.0
- MongoDB version: MongoDB shell version v4.2.5
- Pydantic infos (output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())`): 1.7.3
- Python 3.9.1

- Version of additional modules (if relevant):
 

**Additional context**

_Add any other context about the problem here._

**Comment by art049** [comment]
Totally agree, i will fix this example problem.
