### ISSUE TITLE
cannot accesss to http://art049.github.io/odmantic

### ISSUE THREAD

**Issue by luohuan** [art049/odmantic#12]
cannot accesss to http://art049.github.io/odmantic

**Comment by art049** [comment]
Hello, can you provide me a few details ?
- what browser are you using ?
- does it work if you try to access the httpS url directly: https://art049.github.io/odmantic/ ?
- do you have errors displaying in the browser console / network tab ?

**Comment by luohuan** [comment]
i am sorry  is my dns problem
