### ISSUE TITLE
KeyError when reading documents with unset fields

### ISSUE THREAD

**Issue by dang-cb** [art049/odmantic#13]
I am using FastAPI and odmantic to access an existing MongoDB data source. I have constructed an odmantic [Model](https://art049.github.io/odmantic/api_reference/model/#odmantic.model.Model) for an existing collection for users:
```
class User(Model):
    __collection__ = "users"
    name: str = Field(max_length=50)
    email: str = Field(max_length=150)  # unique=True
    password: bytes
    logged_in: Optional[datetime.datetime]
```
When a ```User``` record is created, the ```logged_in``` property will be null/None.

In a pure odmantic environment, the ```logged_in``` property would still be persisted to the MongoDB document with a null/None value.

However, [mongoengine](http://mongoengine.org/) by default an optional field will not set at all, so for the model above the logged_in field will not appear in the document at all.

This means that when odmantic encounters users that have never logged in, an error is raised:
```
File "~/lib/python3.8/site-packages/odmantic/model.py", line 547, in parse_doc
  doc[field_name] = raw_doc[field.key_name]
KeyError: 'logged_in'
```

As accessing existing data sources is likely to be a common scenario with odmantic, it would be good to determine how best to handle this, both for reading and writing data.

**Comment by art049** [comment]
I think a way to solve this, will be to populate the field with it's default value when the document doesn't contain the field. The fix should be released soon.

**Comment by dang-cb** [comment]
Oh lovely, thank you  👍 

I guess default value, or simply ```None``` if no default value has been specified.
