### ISSUE TITLE
Defining `__init__` in model throws `TypeError`

### ISSUE THREAD

**Issue by joeriddles** [art049/odmantic#148]
# Bug

Defining `__init__` in a model that inherits from `odmantic.Model` raises `TypeError`.

### Current Behavior

```python
from odmantic import Model

class MyModel(Model):
  def __init__(self, **data):
    super().__init__(**data)
```
throws `TypeError: __class__ set to <class '__main__.MyModel'> defining 'MyModel' as <class '__main__.MyModel'>`

### Expected behavior

Defining `__init__` does not raise an error.

### Environment

- ODMantic version: 0.3.5
- MongoDB version: N/A
- Pydantic infos (output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())`):
```
pydantic version: 1.8.2
            pydantic compiled: True
                 install path: ...\.venv\Lib\site-packages\pydantic
               python version: 3.9.3 (tags/v3.9.3:e723086, Apr  2 2021, 11:35:20) [MSC v.1928 64 bit (AMD64)]
                     platform: Windows-10-10.0.19041-SP0
```

**Comment by art049** [comment]
For now manually defining an init is not supported but you can define [pydantic root validators](https://pydantic-docs.helpmanual.io/usage/validators/#root-validators)(which are totally supported) to achieve the same result.
