### ISSUE TITLE
Conflicting modules

### ISSUE THREAD

**Issue by vd2org** [art049/odmantic#154]
# Bug

`bson`, `typing` and `fastapi` modules conflict with modules installed in virtual env. Since PyCharm adds current source root directories in sys.path, odmantic cannot be debugged or used as linked project in PyCharm.

### Environment

- ODMantic version: current master
- PyCharm 2021.1.3
- Python 3.9.6

**Comment by art049** [comment]
Can you add more details (screenshots maybe) on the problem? It doesn't seem very easy to reproduce right now.
