### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Youngestdev** [art049/odmantic#158]
First, thank you for this project! It has made using MongoDB and fastapi smooth! 

However, is there support for pagination?

**Comment by chrisdewa** [comment]
What do you mean by pagination? can you provide an example?

**Comment by Youngestdev** [comment]
Hi!

Something similar to what https://pypi.org/project/PyMongonnator does.

Maybe something like this where we can return items in batch>
```py
engine.paginate(Model, condition)

**Comment by hellocoldworld** [comment]
I am currently resolving this using

```python
engine.find(Tree, start=start, limit=limit, sort=sort_expression)
```

The only thing I am missing is the projection operators.

**Comment by Youngestdev** [comment]
Oh wow! Thanks for this.

**Comment by Youngestdev** [comment]
So how will you split a database of 1000 entries into batches that's returned on request? 🤔

**Comment by chrisdewa** [comment]
I kept thinking about this issue and I came up with a partial solution. 
An async generator that could work.

I tested in on one of my databases and the results were good enough.

```python
async def paginate(engine, obj, *query, sort=None,  chunk_size=10, total_limit=None):
    skip = 0
    while True:
        batch = await engine.find(
            obj,
            *query,
            skip=skip,
            limit=chunk_size,
            sort=sort
        )
        chunk = len(batch)
        skip += chunk
        if skip + chunk_size > total_limit:
            chunk_size = total_limit - skip
        yield batch
        if chunk < chunk_size or (total_limit and skip >= total_limit):
            break
```
It'd work like this:
```python
async for batch in paginate(engine, Tree, Tree.average_size.gt(2), sort=Tree.average_size.desc(),
                                             total_limit=19, chunk_size=5):
        print(batch)
```
Each batch would be a list of Trees.


Perhaps something like this would work for you?

**Comment by Youngestdev** [comment]
This looks good. But, in an event where each batch is returned at a GET request, e.g:
1.  `/route/1` returns the first batch
2. `/route/2` returns the second batch and so on.

What happens to the for loop? Naive me thinks storing the batches in a document batches can be returned individually but that's expensive.

**Comment by Youngestdev** [comment]
I will try to come up with something and if it works, I'll update this thread. I might eventually have to store the batches in a tree in-memory or smtn.

**Comment by hellocoldworld** [comment]
Sorry maybe I man missing something or didn't understand the issue, but what is the problem with the following FastAPI app?


```
from fastapi import FastAPI
from odmantic import *

PAGE_SIZE = 10

class Tree(Model):
    name: str
    average_size: float
    discovery_year: int

app = FastAPI()

engine = AIOEngine()

@app.get("/route/{page_number}")
async def get_trees(page_number: int):
	start = page_number*PAGE_SIZE
	trees = await engine.find(Tree, skip=start, limit=PAGE_SIZE)
	return trees

if __name__ == '__main__':
    import asyncio
    import uvicorn
    loop = asyncio.get_event_loop()
    config = uvicorn.Config(app=app, port=8080, loop=loop)
    server = uvicorn.Server(config)
    loop.run_until_complete(server.serve())
```

**Comment by Youngestdev** [comment]
Oh, this looks cool!

**Comment by tyteen4a03** [comment]
+1 - would be great if cursor-based pagination also came out of the box.
