### ISSUE TITLE
Add support for motor 2.5

### ISSUE THREAD

**Issue by tyteen4a03** [art049/odmantic#172]
Motor 2.5 was released in July. It would be great if odmantic can support it.

**Comment by athulnanda123** [comment]
please add motor2.5 support, this package is nice, please don't make it obsolete

**Comment by jbertman** [comment]
This still being maintained? Tests appear to pass for < 2.6.0: https://github.com/art049/odmantic/pull/160

**Comment by athulnanda123** [comment]
looks like package is no longer maintained, so i migrated my project from odmantic to beanie [https://roman-right.github.io/beanie/](url)

**Comment by art049** [comment]
Done with support for motor 3.0 in 0.5.0 release
