### ISSUE TITLE
Update dependencies and pydantic to version 1.9.0

### ISSUE THREAD

**Issue by Goldziher** [art049/odmantic#206]
Hi there,

I'm the author of a library called [pydantic-factories](https://github.com/Goldziher/pydantic-factories). I support odmantic for a while now. I am updating my library to support pydantic 1.9.0, which was released yesterday. It seems that odmantic is currently incompatible with it. I will continue to support odmantic but will need to remove it from my dev dependencies, and will be forced to comment out parts of the test suite. So I hope you update soon.

**Comment by oktavlachs** [comment]
Any update on this?

**Comment by erny** [comment]
Is it normal that the checks take so much time to run?

**Comment by art049** [comment]
Not really, I'll trigger it again. Supporting this new version also requires a bit of refactoring so it might take a bit more time.
