### ISSUE TITLE
docs: typo 

### ISSUE THREAD

**Issue by linpan** [art049/odmantic#256]
docs have error : engine = AIOEngine(motor_client=client, database="example_db")

motor_client to client instead .

` def __init__(
        self,
        client: Union["AsyncIOMotorClient", None] = None,
        database: str = "test",
    ):
        """Engine constructor.

        Args:
            client: instance of an AsyncIO motor client. If None, a default one
                    will be created
            database: name of the database to use

        
        """`

**Comment by art049** [comment]
Thanks for noticing this !
