### ISSUE TITLE
How to exclude fields when querying ?

### ISSUE THREAD

**Issue by ermal-abiti** [art049/odmantic#268]
I have this user model that looks like this,
```python
class UserModel(Model):
    email: str = Field(unique=True)
    username: str = Field(unique=True)
    password: str
    role: str

    class Config:
        collection = 'users'
```

and this api endpoint to fetch users,
```python
@router.get('/')
async def get_all_users():
    users = await engine.find(UserModel)
    return users
```
Response:
```json
[
  {
    "email": "string",
    "username": "string",
    "password": "string",
    "role": "string",
    "id": "63242fa82ee84fbe97fa563e"
  },
  {
    "email": "string",
    "username": "string",
    "password": "string",
    "role": "string",
    "id": "632431405f3eafbf007afe45"
  }
]
```

**How can i exclude the `password` field, so it wont show in the response object ?**
Ex.
```json
[
  {
    "email": "string",
    "username": "string",
    "role": "string",
    "id": "63242fa82ee84fbe97fa563e"
  },
...
```

**Comment by linpan** [comment]
simple way :  https://fastapi.tiangolo.com/tutorial/response-model/#response_model_include-and-response_model_exclude

**Comment by art049** [comment]
Another possibility is to create a Pydantic Schema for your API I/Os. And in this schema, you can exclude unwanted fields.
For example: 

https://github.com/art049/fastapi-odmantic-realworld-example/blob/4624d65844fb47db39c57f5898ab14e3eb84e386/src/endpoints/user.py#L47-L51
