### ISSUE TITLE
Using the sorting method leads to an analysis error in PyCharm

### ISSUE THREAD

**Issue by vd2org** [art049/odmantic#27]
PyCharm does not see the `asc` and `desc` methods in model fields.

`MyModel.timestamp.asc()` displayed as error.

`query.asc(MyModel.timestamp)` looks fine.

Of course both methods work fine.

**Comment by art049** [comment]
Yes, it's mentionned in the docs already but maybe it's not explicit that it might raise errors with pycharm as well.
![image](https://user-images.githubusercontent.com/15641577/97290710-396c2500-1849-11eb-9859-3240de327217.png)
Maybe changing this "note" to a warning could help ?
