### ISSUE TITLE
When the time is inserted into the database

### ISSUE THREAD

**Issue by InfernalAzazel** [art049/odmantic#330]
The bug that the date is wrong when the time is inserted into the database
e.g: 2023-2-3 inserted 2023-1-17

**Comment by santigandolfo** [comment]
Could you write an example when that happens?

**Comment by InfernalAzazel** [comment]
> Could you write an example when that happens?
Dude, I remember adding other time zones and then adding them. I asked a few questions before, and the activity level was not high. Later, I deleted the project code that used odmantic, so I don't remember the detailed questions at that time.
