### ISSUE TITLE
Model.copy is not implemented

### ISSUE THREAD

**Issue by vd2org** [art049/odmantic#34]
When trying to call the Model.copy method, a NotImplementedError occurs.

So, it is hard to partially update models data.

Workaround:

```python
obj = await engine.find_one(ObjModel, ObjModel.id == some_object_id)
data = {**obj.dict(), **other.dict(exclude_unset=True, exclude_none=True)}
obj = ObjModel(**data)
```

**Comment by art049** [comment]
Yes, totally agree.

**Comment by art049** [comment]
It will now be possible to use the `Model.update` method to solve this issue
