### ISSUE TITLE
Add support for Pydantic V2

### ISSUE THREAD

**Issue by santigandolfo** [art049/odmantic#359]
# Feature request

### Context

Pydantic v2 already out and odmantic doesn't work with it. For example, if I try to use it in a FastAPI project (that also released a beta version that supports pydantic v2) I get this error:
```
pydantic.errors.PydanticImportError: `pydantic.datetime_parse:parse_datetime` has been removed in V2.
```

### Solution

It would be nice if odmantic could add support for Pydantic v2.

**Comment by Kludex** [comment]
Let us know if help is needed. 🙏

**Comment by art049** [comment]
Hey, I started working on the support last week. 
Quite a lot of model logic ends up changed but I'm almost there. I'll publish the first PR as soon as it starts passing the first tests so we can iterate on it!

**Comment by cat-turner** [comment]
Thanks for working on this @art049 is there an update? I can test this with my repo

**Comment by alliefitter** [comment]
Is this close to being released?

**Comment by ahmedivy** [comment]
I spend two days modelling my database (writing model classes) just to find out that it is not compatible with fastapi because of PyDantic 2 🥲

**Comment by art049** [comment]
> Is this close to being released?

I think so, at least a first beta. However, this will be a breaking change, and supporting both versions of Pydantic will be extremely painful.

Also, I got some ideas to improve the performance with Pydantic v2, I will try to share some  PoCs soon :crab: :rocket:

**Comment by alliefitter** [comment]
Cool. My company's generous with time for open source work, so shoot me a
message if you need any help.

**Comment by psharrma** [comment]
Hi,

We have a dependency on pyDantic v2, We like the library but this issue is holding us back.

**Comment by alliefitter** [comment]
@art049 Is there any plan of getting a beta release on PyPI? We have a project that's held up on upgrading to Pydantic 2, as well, and if you were to release a beta, we'd be able to get you some feedback.

**Comment by Theodlz** [comment]
Hi @art049. Thanks a lot for working on this. Any idea if a PR or a release will be ready before October?
Let me know if I can help.

**Comment by KShah707** [comment]
Same here, this is a dealbreaker for us

**Comment by MahmudulHassan5809** [comment]
hi any update ?

**Comment by Kludex** [comment]
I'm going to unsubscribe given the amount of spam, but if you need help, feel free to ping me. 👍
