### ISSUE TITLE
Timestamp field

### ISSUE THREAD

**Issue by avaldevilap** [art049/odmantic#36]
```python
from datetime import datetime

from odmantic import Model
from pydantic import EmailStr


class Subscriber(Model):
    email: EmailStr
    subscribed_at: datetime = datetime.utcnow()
```
Trying to make a timestamp field, but I get the error: Value not declarable with JSON Schema

**Comment by dang-cb** [comment]
You’ve defined subscribe_at as a “date” field, and then are setting its default value to datetime.

Try subscribed_at: datetime = datetime.utcnow()



On 3 Nov 2020, at 02:12, Alejandro Valdevila Pérez <notifications@github.com> wrote:

﻿

from datetime import datetime

from odmantic import Model
from pydantic import EmailStr


class Subscriber(Model):
    email: EmailStr
    subscribed_at: date = datetime.utcnow()

Trying to make a timestamp field, but I get the error: Value not declarable with JSON Schema

**Comment by avaldevilap** [comment]
Sorry my bad, I actually defined it as a datetime 😅
