### ISSUE TITLE
Links with target=blank in contributing.md displays wrong and doesn't open in new window

### ISSUE THREAD

**Issue by sanders41** [art049/odmantic#4]
Links in the contributing.md file with :target=blank_ displays the target=blank_ part and does not open in a new tab. For example:

> If you want to contribute (thanks a lot ! :smiley:), you can open an [issue](https://github.com/art049/odmantic/issues/new){:target=blank_}.

I'm not sure of a way to make the {"target=blank_"} part work correctly so it seems like the best solution would be to remove it? If you would like I could open a PR removing the {:target-blank_} part.

**Comment by sanders41** [comment]
I just noticed it looks and functions normal on GitHub pages and only looks weird when viewed elsewhere (i.e. on GitHub) so maybe this is how it is intended?

**Comment by art049** [comment]
Hello, thanks for the feedback, actually as you noticed, this contributing.md file is supposed to be rendered by mkdocs (should be only checked from the documentation).
I think to avoid confusion, we could add a `CONTRIBUTING.md` file in the root directory of the repository. This file would display a link to the Contributing section of the docs  https://art049.github.io/odmantic/contributing/ . Thus it would be easier to find the Contributing help from the repository directly.
