### ISSUE TITLE
when a model has many optional field, it will raise unwanted validation type error 

### ISSUE THREAD

**Issue by brightgems** [art049/odmantic#407]
# Bug

it will raise unwanted validation type error when a model has many optional field;
pydantic won't raise any error

from odmantic import Model,Field
from pydantic import BaseModel
from typing import Optional, Dict

class DummpyEmbedModel(Model):
    """item url and title, thumbnail
    treat as task queue
    """
    infos: Optional[Dict] = None
    # all image text in item page
    pso: Optional[str] = None
    gptTags: Optional[Dict] = None
    

### Current Behavior
```
self = DummpyEmbedModel(), data = {'infos': {}, 'pso': 'xx'}

    def __init__(self, **data: Any):
>       super().__init__(**data)
E       pydantic_core._pydantic_core.ValidationError: 1 validation error for DummpyEmbedModel
E       pso
E         Input should be a valid dictionary [type=dict_type, input_value='xx', input_type=str]
E           For further information visit https://errors.pydantic.dev/2.5/v/dict_type
```
### Expected behavior

should no raise any error as pydantic

### Environment

- ODMantic version: ...
- MongoDB version: ...
- Pydantic infos (output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())`):

```

class DummpyEmbedModel(Model):
    """item url and title, thumbnail
    treat as task queue
    """
    infos: Optional[Dict] = None
    # all image text in item page
    pso: Optional[str] = None
    gptTags: Optional[Dict] = None
    
...
```

- Version of additional modules (if relevant):
  - ...

**Additional context**

v1.0.0

**Comment by laveolus** [comment]
In v1.0.0, all optional fields are aliased to the (first) field type, see #379.

**Comment by francisdeh** [comment]
@laveolus and @brightgems, until this is addressed, have you found any temporary workaround to this? I also encountered same.

**Comment by pr0gg3d** [comment]
We are also plenty of Optional[] fields with different types, and this makes odmantic 1.0.0 pretty much unusable.

Anyone found a workaround for this? Thanks!!

**Comment by Jibola** [comment]
> @laveolus and @brightgems and @Jibola, until this is addressed, have you found any temporary workaround to this? I also encountered same.

Currently, I have just leveraged the Pydantic `BaseModel` class as my workaround for now. If it's unavoidable, I've settled for removing the Optional field usage.
