### ISSUE TITLE
ODMantic is incompatible with pydantic version 2.7.0

### ISSUE THREAD

**Issue by MickVermeulen** [art049/odmantic#451]
# Bug

When updating to [pydantic version 2.7.0](https://pypi.org/project/pydantic/2.7.0/), `pydantic` will throw a `PydanticUserError` due to ODMantic trying to use `model_config` as a model field name. More info: https://errors.pydantic.dev/2.7/u/model-config-invalid-field-name

### Current Behavior

```python
# assuming you have pydantic==2.7.0 installed
from odmantic import Model

class Foo(Model):
    foo: str

if __name__ == '__main__':
    foo = Foo(foo='bar') # raises pydantic.errors.PydanticUserError
```

### Expected behavior

I expect it to not throw an error

### Environment

- ODMantic version: 1.0.1
- Pydantic version: 2.7.0
- MongoDB version: any

```
pydantic version: 2.7.0
pydantic-core version: 2.18.1
pydantic-core build: profile=release pgo=true
python version: 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
platform: macOS-13.5.2-arm64-arm-64bit
related packages: typing_extensions-4.9.0 fastapi-0.110.1 pydantic-settings-2.2.1
```

**Comment by munishkhatri720** [comment]
The same issue occurred with me, but it was fixed by reverting the Pydantic version from 2.7.0 to 2.6.4.

**Comment by abhinna1** [comment]
Seems like Pydantic 2.70 had some major changes. You can read more [here](https://blog.pydantic.dev/blog/2024/04/11/2-7-release/#performance-improvements
).

Reverting Pydantic version to any previous versions above `2.5.2`, preferably `2.6.4` solves the issue for now.

**Comment by adriencaccia** [comment]
Thanks for the issue @MickVermeulen, #462 should fix it!
The release is coming soon.

**Comment by adriencaccia** [comment]
Fixed in https://github.com/art049/odmantic/releases/tag/v1.0.2
