### ISSUE TITLE
AIOEngine的最佳实践是什么，

### ISSUE THREAD

**Issue by f754699** [art049/odmantic#495]
我想知道AIOEngine数据库连接的使用的最佳方式是什么，
是在收到每个请求的时候创建一个新的连接，
还是一直复用同一个数据库连接？？

你们都是怎么使用的？？

**Comment by TnTomato** [comment]
It's built on top of Motor. Motor is built on top of PyMongo. So, you can use a single instance everywhere in your application because PyMongo provides built-in connection pooling. [see here](https://pymongo.readthedocs.io/en/stable/faq.html#how-does-connection-pooling-work-in-pymongo)

**Comment by f754699** [comment]
好吧
