### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by ramzitannous** [art049/odmantic#55]
@art049  Great library looks very promising, but there is 2 missing features I think which are:
1. Model inheratance (maybe available but not documented)
2. Mongodb Migration 
And I can contibute if needed.

**Comment by art049** [comment]
Hey, thanks for the feedback !
Yes, the inheritance is not supported yet. Actually it might be a part of solving #60  as well.
For the Migration, I totally agree; that would be awesome. I you have some ideas, don't hesitate to open an issue so we can discuss it in depth.
