### ISSUE TITLE
try update __odm_fields__ from a second parent class ...

### ISSUE THREAD

**Issue by Barceloch** [art049/odmantic#57]
waiting model inherance... :)

**Comment by Barceloch** [comment]
o_O if I do the following it seems to work but I don't think it's the right?, the documentation says that is how I was trying before

class ContactModel(Model):
    fullname: str
    phone: str
    email: str
    __collection__ = "Contacts"

**Comment by art049** [comment]
Actually model inheritance is not supported yet.
It should work like this though:

```
from odmantic import Model

class ContactModel(baseModel):
    class Config:
        collection = "__Contacts"    # <---------------*it this will be a dynamic custom name  for all my models*

    fullname: str
    phone: str
    email: str

**Comment by Barceloch** [comment]
> Actually model inheritance is not supported yet.
> It should work like this though:
> 
> ```
> from odmantic import Model
> 
> class ContactModel(baseModel):
>     class Config:
>         collection = "__Contacts"    # <---------------*it this will be a dynamic custom name  for all my models*
> 
>     fullname: str
>     phone: str
>     email: str  
> ```
I was edited the firth comment, can you give me some suggest to achieve that from the better way?
