### ISSUE TITLE
Check connection to db

### ISSUE THREAD

**Issue by tobiasz-gleba** [art049/odmantic#58]
How to check connection to mongoDB using odmantic?

**Comment by art049** [comment]
Hello, you mean to check if the mongo server is up ?

**Comment by TobiaszG24** [comment]
yup

**Comment by art049** [comment]
Right now, there is nothing unfortunately. If the database is not there, the motor_client will hang.
This is the default behavior of motor but maybe it would be possible to add a timeout flag.
