### ISSUE TITLE
Update Raw Query Usage Documentation

### ISSUE THREAD

**Issue by adeelsohailahmed** [art049/odmantic#6]
Hi! First of all, thank you for sharing your amazing project. I've already started using it in my code.

I noticed two mistakes in the Raw Query Usage section of the documentation:

1. [Creating instances from a raw documents](https://art049.github.io/odmantic/raw_query_usage/#creating-instances-from-a-raw-documents) states that the **parse_doc** method can be used to create new instance from a raw document. However, the example code shows the extraction of document from an existing instance.

2. Similarly, section [Extract documents from existing instances](https://art049.github.io/odmantic/raw_query_usage/#extract-documents-from-existing-instances) states that the **doc** method can be used to extract document from existing instance. However, the example code shows the creation of a new instance from a raw document.

Upon investigation, I found that the code snippets had been referenced correctly in raw_query_usage.md but the code snippet files themselves had been incorrectly named.

To fix this:
- I renamed the **create_from_raw.py** to **extract_from_existing.py** (this will also remove any ambiguity from the name). 
- Then, I renamed the **extract_from_raw.py** to **create_from_raw.py**. 
- Lastly, I update the **raw_query_usage.md** to reference the newly renamed files.

You can view my commits [here](https://github.com/adeelsohailahmed/odmantic/commits/raw_query_usage_fix). If you think it's good enough, I can send in a pull request.

PS: I noticed at least one typo, but those are fine by me. ;) If you want, I can fix the typos before I send in a pull request.

**Comment by art049** [comment]
Hi, first thanks for the thourough look to the docs :grinning: .
Your changes looks good to me. (Maybe you can squash those commits though)

For the other typos, definetly I would be glad if you still have them in mind and can fix them as well :ok_hand: .

**Comment by adeelsohailahmed** [comment]
Thank you for your kind reply!

I found a typo in this section (a wayward 'a' in from **Creating instances from a raw documents** heading) which I've removed. I've sent a pull request. 

Looking forward to contribute as much I can.

Regards,
Adeel

**Comment by art049** [comment]
Thanks a lot !
