### ISSUE TITLE
Replace (or remove) `id` field description

### ISSUE THREAD

**Issue by Olegt0rr** [art049/odmantic#79]
# Feature request

### Context
Now the `id` field is printed in documents with information about the used database:
`MongoDB ObjectId string`

I'm not sure if showing this information is a good idea.
What kind of database and what kind of identifier generation are used to store the data is not a client's business.

### Solution
I suggest removing the description of the `id` field. This will hide unnecessary information from the user.

#### Alternative solutions
It will also be great if `odmantic` will be able to specify a custom description and parameters for `id` field

#### Additional context
It would also be great to make the example look more similar. 
I.e. replace `ffffffffffffffffffffffff` with `5f85f36d6dfecacc68428a46`

**Comment by Olegt0rr** [comment]
Solution to hide this description described in https://github.com/art049/odmantic/issues/75
But I'm still suggesting to remove current description as I wrote above

**Comment by Olegt0rr** [comment]
Bad news, it's not a solution.

```id: ObjectId = Field(primary_field=True, description='My ID')``` is overwrited by `MongoDB ObjectId string` description :(

**Comment by adeelsohailahmed** [comment]
> Bad news, it's not a solution.

My solution was specific to that issue. The user wanted to use their own strings for `id` field for their own model instead of letting ODMantic generate `id` itself.

**Comment by art049** [comment]
Replacing the default example is totally good to me.
We can as well  remove the default description.

> What kind of database and what kind of identifier generation are used to store the data is not a client's business.
Unfortunately, it's a bit linked. Since we perform ObjectId validation, passing an invalid id (like a non hex string) will raise a validation error.
We can still remove the description since it's overriding everything right now though.
