### ISSUE TITLE
Can't use an EmbeddedModel as a primary field

### ISSUE THREAD

**Issue by suconakh** [art049/odmantic#94]
# Bug

ODMantic can't save document to database when primary field of a document is EmbeddedModel.

### Current Behavior

When defining EmbeddedModel as a primary field of a Model:
```python
class Id(EmbeddedModel):
    user: int
    chat: int


class User(Model):
    id: Id = Field(primary_field=True)
```
ODMantic refuses to save the document into database:
```python
user = User(id=Id(user=1, chat=1001))
await engine.save(user)
```
It either does nothing as if operation was successful, or throws an error:
```python
bson.errors.InvalidDocument: cannot encode object: Id(user=1, chat=1001), of type: <class '__main__.Id'>
```
However everything is ok if i do this:
```python
await engine.get_collection(User).insert_one(user.doc())
```

Also everything is good with queries:
```python
user = await engine.find_one(User)
print(user) 
print(user.id)
print(user.id.chat)

# id=Id(user=1, chat=1001)
# user=1 chat=1001
# 1001

```

### Expected behavior

ODMantic should work fine with EmbeddedModel as primary field of a Model

### Environment

- ODMantic version: 0.3.2
- MongoDB version: 4.2.11
- Pydantic infos (output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())`):

```
pydantic version: 1.7.3
            pydantic compiled: True
                 install path: D:\_Projects\python\bot\py\Lib\site-packages\pydantic
               python version: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
                     platform: Windows-10-10.0.18362-SP0
     optional deps. installed: ['typing-extensions']
```

**Comment by richiq** [comment]
I had the same issue with [umongo](https://github.com/Scille/umongo/issues/338#issuecomment-762451600) and thanks to @lafrech i was able to fix it in odmantic by changing this:
https://github.com/art049/odmantic/blob/dfa023cc7f5e4971d07037c02d9daa9405d4d334/odmantic/engine.py#L316
To this:
```python
 instance.doc(include=instance.__primary_field__),
```

I don’t think I have enough knowledge to test this properly, so I’ll be glad if someone tests this and makes a pull request.

**Comment by mukesh5** [comment]
@richiq which is better between umongo and odmantic. I have just started using FastAPI and want to connect with MongoDB. Which is rather easy to use between umongo and odmantic or should I rather go with Motor Client?
