### ISSUE TITLE
pydantic ValidationError for datetime fields if microsecond is 999xyz

### ISSUE THREAD

**Issue by erny** [art049/odmantic#99]
# Bug

Creating a model instance with datetime fields fail if microseconds is between 999500 and 999999.
This seems to be a rounding error.

### Current Behavior

```python
import datetime
from odmantic import Model

class MyModel(Model):
    date_time: datetime.datetime


instance = MyModel(date_time=datetime.datetime.now().replace(microsecond=999500))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "services/registry/.venv/lib/python3.8/site-packages/odmantic/model.py", line 481, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MyModel
date_time
  microsecond must be in 0..999999 (type=value_error)
```

### Expected behavior

No validation error should be raised.

I'm not sure if datetimes with microseconds > 999500 should be rounded up to the next second or not. Most implementations do not round, but just crop the last three digits of microseconds like these:
* now.isoformat(sep=' ', timespec='milliseconds')
* now.strftime("%H:%M:%S.%f")[:-3]

We could use the following expression to crop: 
```python
now = now.replace(microsecond=now.microsecond-now.microsecond % 1000)
```

### Environment

- ODMantic version: 0.3.2
- MongoDB version: 4.4
- Pydantic: 1.7.:
- python: 3.8.5
```
print(pydantic.utils.version_info())
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: services/registry/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Sep  7 2020, 19:43:22)  [Clang 10.0.0 (clang-1000.11.45.5)]
                     platform: macOS-10.14.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions', 'email-validator']
```

**Comment by art049** [comment]
> I'm not sure if datetimes with microseconds > 999500 should be rounded up to the next second or not.

Nice catch, the truncation is totally ok to me :+1:

**Comment by art049** [comment]
Thanks @erny !

**Comment by erny** [comment]
Thanks so much!
